-- Migration 047: job_type_presets + preset_bookings (CEO orchestration presets)
-- Run: psql "$DATABASE_URL" -f migrations/047_job_type_presets.sql

CREATE TABLE IF NOT EXISTS job_type_presets (
    preset_id       TEXT PRIMARY KEY,
    job_type        TEXT NOT NULL,
    description     TEXT NOT NULL,
    trigger_hint    TEXT,
    agent_slots     JSONB NOT NULL DEFAULT '[]',
    kpi_targets     JSONB NOT NULL DEFAULT '{}',
    is_active       BOOLEAN DEFAULT true,
    usage_count     INTEGER DEFAULT 0,
    created_at      TIMESTAMPTZ DEFAULT now(),
    updated_at      TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS preset_bookings (
    booking_id      BIGSERIAL PRIMARY KEY,
    job_id          UUID REFERENCES jobs(id) ON DELETE CASCADE,
    preset_id       TEXT REFERENCES job_type_presets(preset_id),
    agent_id        TEXT REFERENCES hired_agents(agent_id),
    slot_role       TEXT NOT NULL,
    deviation       BOOLEAN DEFAULT false,
    deviation_reason TEXT,
    booked_at       TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_presets_active ON job_type_presets(is_active);
CREATE INDEX IF NOT EXISTS idx_preset_bookings_job ON preset_bookings(job_id);
CREATE INDEX IF NOT EXISTS idx_preset_bookings_preset ON preset_bookings(preset_id);

INSERT INTO job_type_presets (preset_id, job_type, description, trigger_hint, agent_slots, kpi_targets) VALUES
('seo-content-campaign','SEO Content Campagne','Keyword-gedreven content die autoriteit opbouwt','seo, blog, content, artikel, pillar page, zoekwoorden, organic','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"strategist","role":"SEO Content Strategist","agent_type":"worker","persona":"Mike Ross","required":true},{"slot":"copywriter","role":"Copywriter","agent_type":"worker","persona":"Forrest Gump","required":true},{"slot":"reviewer","role":"SEO Reviewer / QA","agent_type":"talent","persona":"Alan Turing","required":true},{"slot":"distribution","role":"Distribution Strategist","agent_type":"worker","persona":"Keanu Reeves","required":false}]','{"kpis":["Organisch verkeer +X% binnen 90 dagen","Top-10 voor target keywords"],"outputs":["Pillar page","Cluster artikelen","Distributiebriefing"]}'),
('paid-ads-launch','Paid Ads Launch','Van briefing naar live campagne met gevalideerde creatives','ads, campagne, advertentie, media, facebook, google ads, budget, roas','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"scriptwriter","role":"Scriptwriter & Hook Specialist","agent_type":"worker","persona":"Ferris Bueller","required":true},{"slot":"media_buyer","role":"Media Buyer","agent_type":"worker","persona":"Winston Wolf","required":true},{"slot":"tracking","role":"Tracking Architect","agent_type":"worker","persona":"Q","required":true},{"slot":"reviewer","role":"QA Reviewer","agent_type":"talent","persona":"Patrick Bateman","required":true}]','{"kpis":["ROAS target behaald binnen 14 dagen","CPM/CPC binnen benchmarks"],"outputs":["Campagnestructuur","Gevalideerde creatives","Tracking rapport"]}'),
('ecommerce-launch','E-commerce Product Launch','Van productinformatie naar geoptimaliseerde pagina','product launch, webshop, productpagina, shopify, wordpress, collectie','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"coo","role":"COO Coordinator","agent_type":"coo","persona":"Mr. Klein","required":true},{"slot":"merchandising","role":"Merchandising & Pricing","agent_type":"worker","persona":"Man with No Name","required":true},{"slot":"copywriter","role":"Copywriter","agent_type":"worker","persona":"Forrest Gump","required":true},{"slot":"seo","role":"SEO Specialist","agent_type":"worker","persona":"Donnie Darko","required":true},{"slot":"reviewer","role":"QA Reviewer","agent_type":"talent","persona":"Alan Turing","required":true}]','{"kpis":["SEO-score: APPROVED","Conversion rate boven gemiddelde","Time-to-live <48u"],"outputs":["Productpagina","SEO meta-teksten","Pricing rapport"]}'),
('retention-lifecycle','Retention & Lifecycle Campagne','Klanten activeren voor herhaalaankoop en hogere LTV','retention, lifecycle, churn, loyalty, email flow, herhaalaankoop, ltv','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"insights","role":"Customer Insights Specialist","agent_type":"worker","persona":"Jeffrey Beaumont","required":true},{"slot":"copywriter","role":"Copywriter","agent_type":"worker","persona":"Forrest Gump","required":true},{"slot":"format","role":"Format Developer","agent_type":"worker","persona":"Keanu Reeves","required":false},{"slot":"reviewer","role":"QA Reviewer","agent_type":"talent","persona":"Data","required":true}]','{"kpis":["Repeat purchase rate +X%","LTV stijging binnen 60 dagen"],"outputs":["Win-back flow","Loyalty communicatie","Insights rapport"]}'),
('brand-narrative','Brand Narrative & Strategie','Het merkverhaal definieren dat alle communicatie verankert','merk, brand, positionering, narratief, strategie, tone of voice, brand voice','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"coo","role":"COO Coordinator","agent_type":"coo","persona":"Mr. Klein","required":true},{"slot":"narrative","role":"Narrative Designer","agent_type":"worker","persona":"Jeanne d Arc","required":true},{"slot":"copywriter","role":"Copywriter","agent_type":"worker","persona":"Forrest Gump","required":true},{"slot":"reviewer","role":"QA Reviewer","agent_type":"talent","persona":"Hannibal Lecter","required":true}]','{"kpis":["Brand voice goedgekeurd","Narratief consistent over touchpoints"],"outputs":["Brand story","Tone of voice guide","GTM deck"]}'),
('data-infra-setup','Data & Tracking Infrastructuur','Een schone meetstructuur als fundament voor alle AI-beslissingen','tracking, data, analytics, ga4, gtm, server-side, cdp, dashboard, meting','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"coo","role":"COO Coordinator","agent_type":"coo","persona":"Mr. Klein","required":true},{"slot":"tracking","role":"Tracking Architect","agent_type":"worker","persona":"Agent K","required":true},{"slot":"data_eng","role":"Data Engineer","agent_type":"worker","persona":"Tony Stark","required":true},{"slot":"compliance","role":"Privacy & Compliance","agent_type":"worker","persona":"Agent Smith","required":true},{"slot":"reviewer","role":"QA Reviewer","agent_type":"talent","persona":"Alan Turing","required":true}]','{"kpis":[">95% event accuracy","AVG compliance: APPROVED"],"outputs":["Server-side tracking","Verificatie rapport","BI dashboard"]}'),
('data-query','Data Analyse & Rapportage','Dataverzoeken en analyses op basis van bestaande data','data, analyse, rapport, cijfers, statistieken, inzicht, keyword research, zoekvolume, metrics, performance, resultaten','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"coo","role":"COO Coordinator","agent_type":"coo","persona":"Mr. Klein","required":true},{"slot":"analyst","role":"Data Analyst","agent_type":"worker","persona":"Mike Ross","required":true},{"slot":"reviewer","role":"QA Reviewer","agent_type":"talent","persona":"Alan Turing","required":false}]','{"kpis":["Correcte data-output zonder hallucinaties","Bronvermelding bij elke claim"],"outputs":["Data rapport","Gestructureerde tabel of export"]}'),
('seo-keyword-research','SEO Keyword Research','Keyword analyse via de SEO tool gerouteerd via COO','keyword, zoekwoorden, keyword research, zoekvolume, concurrentie, serp, search intent, diamond pigs, keyword plan','[{"slot":"ceo","role":"CEO Orchestrator","agent_type":"ceo","persona":"Donna Paulsen","required":true},{"slot":"coo","role":"COO Coordinator","agent_type":"coo","persona":"Mr. Klein","required":true},{"slot":"seo","role":"SEO Specialist","agent_type":"worker","persona":"Mike Ross","required":true},{"slot":"reviewer","role":"SEO Reviewer / QA","agent_type":"talent","persona":"Alan Turing","required":false}]','{"kpis":["Keyword plan goedgekeurd door QA","Zoekintentie correct geclassificeerd"],"outputs":["Keyword plan met zoekvolume en intent","Prioriteitenlijst voor content"]}')
ON CONFLICT (preset_id) DO NOTHING;
