-- Extend user_roles with role column (if not exists) and create role_permissions matrix.
-- Existing user_roles already has role from 066; ADD COLUMN IF NOT EXISTS is a no-op then.

ALTER TABLE user_roles ADD COLUMN IF NOT EXISTS role TEXT NOT NULL DEFAULT 'user'
    CHECK (role IN ('super_admin', 'admin', 'user'));

CREATE TABLE IF NOT EXISTS role_permissions (
    role TEXT NOT NULL CHECK (role IN ('super_admin', 'admin', 'user')),
    permission TEXT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT false,
    PRIMARY KEY (role, permission)
);

-- Seed default permissions: super_admin all true, admin/user system.* false
INSERT INTO role_permissions (role, permission, enabled) VALUES
-- super_admin: alles true
('super_admin', 'workspace.dashboard', true),
('super_admin', 'workspace.inbox', true),
('super_admin', 'workspace.job_center', true),
('super_admin', 'workspace.mission_control', true),
('super_admin', 'management.crew', true),
('super_admin', 'management.agents', true),
('super_admin', 'management.newbies', true),
('super_admin', 'management.training_hub', true),
('super_admin', 'management.hr', true),
('super_admin', 'management.ceo_approval', true),
('super_admin', 'management.improvements', true),
('super_admin', 'management.hiring_hall', true),
('super_admin', 'operations.seo_tool', true),
('super_admin', 'operations.developer_bot', true),
('super_admin', 'operations.safety_gate', true),
('super_admin', 'operations.settings', true),
('super_admin', 'knowledge_centre.library', true),
('super_admin', 'knowledge_centre.write_book', true),
('super_admin', 'knowledge_centre.skill_factory', true),
('super_admin', 'knowledge_centre.client_intelligence', true),
('super_admin', 'knowledge_centre.governance', true),
('super_admin', 'knowledge.explainer', true),
('super_admin', 'knowledge.persona', true),
('super_admin', 'knowledge.crew', true),
('super_admin', 'knowledge.personal_projects', true),
('super_admin', 'knowledge.work_team_org', true),
('super_admin', 'knowledge.study', true),
('super_admin', 'knowledge.product_management', true),
('super_admin', 'system.status', true),
('super_admin', 'system.platform_events', true),
('super_admin', 'system.integrations', true),
('super_admin', 'system.api_keys', true),
('super_admin', 'system.users', true),
-- admin: alles true behalve system.*
('admin', 'workspace.dashboard', true),
('admin', 'workspace.inbox', true),
('admin', 'workspace.job_center', true),
('admin', 'workspace.mission_control', true),
('admin', 'management.crew', true),
('admin', 'management.agents', true),
('admin', 'management.newbies', true),
('admin', 'management.training_hub', true),
('admin', 'management.hr', true),
('admin', 'management.ceo_approval', true),
('admin', 'management.improvements', true),
('admin', 'management.hiring_hall', true),
('admin', 'operations.seo_tool', true),
('admin', 'operations.developer_bot', true),
('admin', 'operations.safety_gate', true),
('admin', 'operations.settings', true),
('admin', 'knowledge_centre.library', true),
('admin', 'knowledge_centre.write_book', true),
('admin', 'knowledge_centre.skill_factory', true),
('admin', 'knowledge_centre.client_intelligence', true),
('admin', 'knowledge_centre.governance', true),
('admin', 'knowledge.explainer', true),
('admin', 'knowledge.persona', true),
('admin', 'knowledge.crew', true),
('admin', 'knowledge.personal_projects', true),
('admin', 'knowledge.work_team_org', true),
('admin', 'knowledge.study', true),
('admin', 'knowledge.product_management', true),
('admin', 'system.status', false),
('admin', 'system.platform_events', false),
('admin', 'system.integrations', false),
('admin', 'system.api_keys', false),
('admin', 'system.users', false),
-- user: zelfde als admin
('user', 'workspace.dashboard', true),
('user', 'workspace.inbox', true),
('user', 'workspace.job_center', true),
('user', 'workspace.mission_control', true),
('user', 'management.crew', true),
('user', 'management.agents', true),
('user', 'management.newbies', true),
('user', 'management.training_hub', true),
('user', 'management.hr', true),
('user', 'management.ceo_approval', true),
('user', 'management.improvements', true),
('user', 'management.hiring_hall', true),
('user', 'operations.seo_tool', true),
('user', 'operations.developer_bot', true),
('user', 'operations.safety_gate', true),
('user', 'operations.settings', true),
('user', 'knowledge_centre.library', true),
('user', 'knowledge_centre.write_book', true),
('user', 'knowledge_centre.skill_factory', true),
('user', 'knowledge_centre.client_intelligence', true),
('user', 'knowledge_centre.governance', true),
('user', 'knowledge.explainer', true),
('user', 'knowledge.persona', true),
('user', 'knowledge.crew', true),
('user', 'knowledge.personal_projects', true),
('user', 'knowledge.work_team_org', true),
('user', 'knowledge.study', true),
('user', 'knowledge.product_management', true),
('user', 'system.status', false),
('user', 'system.platform_events', false),
('user', 'system.integrations', false),
('user', 'system.api_keys', false),
('user', 'system.users', false)
ON CONFLICT (role, permission) DO NOTHING;
