import asyncio
from typing import Any, Dict


async def run(payload: Dict[str, Any]) -> Dict[str, Any]:
    """Generate a product copy draft based on payload and store in artifacts.

    This agent DOES NOT push to Shopify. It only returns a draft (content_text)
    and a structured artifact so the orchestrator can persist it.
    """
    # Simulate processing time
    await asyncio.sleep(0.2)

    context = payload.get("context", {})
    product = context.get("product") or {}
    base_title = product.get("title") or "Product"
    # Simple draft generation (placeholder)
    draft = f"{base_title} — Now with improved features.\n\nDescription: This is an autogenerated draft description for {base_title}."

    # Attempt to save draft to product description only if 'apply' flag is present and allowed by ToolsProxy
    applied = False
    tools = payload.get("tools")
    if payload.get("apply") and tools:
        try:
            prod_id = product.get("id")
            resp = tools.call("shopify_admin_api.update_product", prod_id, {"body_html": draft})
            applied = resp.get("status") == "ok"
        except PermissionError:
            applied = False

    return {
        "summary": "copy draft generated",
        "status": "applied" if applied else "draft",
        "artifacts": [
            {
                "name": "product_copy_draft",
                "type": "text",
                "content": None,
                "content_text": draft,
                "storage_path": None,
            }
        ],
        "data": {"draft_text": draft, "applied": applied},
    }
