export const queryKeys = {
  agents: (filters = {}) => ['agents', filters],
  agent: (id) => ['agents', id],
  jobs: (filters = {}) => ['jobs', filters],
  job: (id) => ['jobs', id],
  jobSteps: (jobId) => ['jobs', jobId, 'steps'],
  clients: () => ['clients'],
  client: (id) => ['clients', id],
  knowledge: (filters = {}) => ['knowledge', filters],
  knowledgeItem: (id) => ['knowledge', id],
  hrReport: () => ['hr', 'report'],
  developmentPoints: () => ['hr', 'development-points'],
  trainingRequests: (filters = {}) => ['hr', 'training-requests', filters],
  seoJobs: () => ['seo', 'jobs'],
  seoJob: (id) => ['seo', 'jobs', id],
  inboxSummary: () => ['inbox', 'summary'],
  hrNotifications: () => ['hr', 'notifications'],
  systemEvents: () => ['system', 'events'],
  approvalSummary: () => ['approval', 'summary'],
  health: () => ['health'],
}
